version: '3'

services:            
    genarg:
        build:
            context: ./gen-arg
            dockerfile: Dockerfile
        command: uvicorn predict:app --host 0.0.0.0 --port 5002 --reload
        # command: gunicorn -w 1 -b 0.0.0.0:5000 wsgi:app
        restart: always
        ports:
            - "5002:5002" 
        networks:
            - common
        volumes:
            - ./gen-arg:/app
            - ./shared/models/genarg:/models 

    dygiepp:
        build:
            context: ./dygiepp
            dockerfile: Dockerfile
        command: uvicorn predict:app --host 0.0.0.0 --port 5001 --reload
        # command: gunicorn -w 2 -b 0.0.0.0:5000 wsgi:app
        restart: always
        ports:
            - "5001:5001" 
        networks:
            - common
        volumes:
            - ./dygiepp:/app
            - ./shared/models/dygiepp:/models 

    gtt:
        build:
            context: ./gtt
            dockerfile: Dockerfile
        command: uvicorn model_gtt.predict:app --host 0.0.0.0 --port 5003 --reload
        # command: gunicorn -w 2 -b 0.0.0.0:5000 wsgi:app
        restart: always
        ports:
            - "5003:5003" 
        networks:
            - common
        volumes:
            - ./gtt:/app
            - ./shared/models/gtt:/models 


    controller:
        build:
            context: ./controller
            dockerfile: Dockerfile
        command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
        # command: gunicorn -w 1 -b 0.0.0.0:5000 wsgi:main
        restart: always
        ports:
            - "5000:5000" 
        networks:
            - common
        volumes:
            - ./controller:/app 
            - ./shared/data:/data  
            - ./shared/outputs:/outputs 
            
networks: 
    common:
